# Generated by Django 5.2 on 2026-08-06 01:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_code', models.CharField(max_length=120, unique=True)),
                ('label_en', models.CharField(max_length=180)),
                ('label_fj', models.CharField(blank=True, max_length=180)),
                ('definition_en', models.TextField()),
                ('definition_fj', models.TextField(blank=True)),
                ('data_type', models.CharField(max_length=40)),
                ('allowed_values', models.TextField(blank=True)),
                ('measurement_unit', models.CharField(blank=True, max_length=40)),
                ('required_status', models.CharField(max_length=30)),
                ('data_source', models.CharField(blank=True, max_length=80)),
                ('update_frequency', models.CharField(max_length=40)),
                ('validation_rule', models.TextField(blank=True)),
                ('confidentiality_level', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name_en', models.CharField(max_length=160)),
                ('name_fj', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField()),
                ('numerator_definition', models.TextField(blank=True)),
                ('denominator_definition', models.TextField(blank=True)),
                ('formula_description', models.TextField()),
                ('measurement_unit', models.CharField(max_length=40)),
                ('frequency', models.CharField(default='quarterly', max_length=40)),
                ('geographic_level', models.CharField(max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataExportAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(max_length=80)),
                ('filters_used', models.JSONField(default=dict)),
                ('number_of_records', models.PositiveIntegerField()),
                ('export_reason', models.TextField(blank=True)),
                ('format', models.CharField(max_length=10)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('numerator_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('denominator_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('data_quality_rating', models.CharField(default='unknown', max_length=20)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='analytics.indicatordefinition')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.province')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.reportingperiod')),
                ('tikina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.tikina')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.village')),
            ],
        ),
    ]
