# Generated by Django 5.2 on 2026-08-06 00:45

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('quarter', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('submission_due_date', models.DateField()),
                ('is_open', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-year', '-quarter'),
                'constraints': [models.UniqueConstraint(fields=('year', 'quarter'), name='unique_reporting_year_quarter'), models.CheckConstraint(condition=models.Q(('quarter__gte', 1), ('quarter__lte', 4)), name='valid_reporting_quarter'), models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='period_start_before_end'), models.CheckConstraint(condition=models.Q(('submission_due_date__gte', models.F('end_date'))), name='period_due_on_or_after_end')],
            },
        ),
        migrations.CreateModel(
            name='TNKReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready_for_validation', 'Ready for validation'), ('submitted', 'Submitted'), ('under_tikina_review', 'Under Tikina review'), ('returned_to_village', 'Returned to village'), ('under_provincial_review', 'Under provincial review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked'), ('archived', 'Archived')], db_index=True, default='draft', max_length=40)),
                ('collection_started_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('district_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('provincial_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('completeness_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('data_quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('verification_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('timeliness_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('evidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_risk_level', models.CharField(choices=[('unknown', 'Unknown'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='unknown', max_length=20)),
                ('roko_veivuke_comment', models.TextField(blank=True)),
                ('provincial_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_tnk_reports', to=settings.AUTH_USER_MODEL)),
                ('previous_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsequent_reports', to='reporting.tnkreport')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reporting.reportingperiod')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tnk_reports', to='locations.village')),
            ],
            options={
                'ordering': ('-reporting_period__year', '-reporting_period__quarter', 'village__name_en'),
            },
        ),
        migrations.CreateModel(
            name='ReportSectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(choices=[('village_profile', 'Village profile'), ('leadership_governance', 'Leadership and governance'), ('visits_training', 'Visits and training'), ('population_households', 'Population and households'), ('housing_assets', 'Housing and village assets'), ('water', 'Water'), ('sanitation_waste', 'Sanitation and waste'), ('energy', 'Electricity and energy'), ('health', 'Health'), ('disability', 'Disability'), ('agriculture_food', 'Agriculture and food security'), ('business_finance', 'Business and village finance'), ('ivdp_projects', 'IVDP projects'), ('climate_disaster', 'Climate and disaster preparedness'), ('traditional_culture', 'Traditional leadership and culture'), ('evidence_declarations', 'Evidence and declarations'), ('validation_submission', 'Validation and submission')], max_length=40)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('complete', 'Complete'), ('needs_attention', 'Needs attention'), ('verified', 'Verified')], default='not_started', max_length=30)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('issue_count', models.PositiveIntegerField(default=0)),
                ('confirmed_unchanged', models.BooleanField(default=False)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_report_sections', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_statuses', to='reporting.tnkreport')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.AddIndex(
            model_name='tnkreport',
            index=models.Index(fields=['status', 'reporting_period'], name='report_status_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='tnkreport',
            constraint=models.UniqueConstraint(fields=('village', 'reporting_period'), name='unique_village_reporting_period'),
        ),
        migrations.AddConstraint(
            model_name='reportsectionstatus',
            constraint=models.UniqueConstraint(fields=('report', 'section_code'), name='unique_report_section'),
        ),
    ]
