# Generated by Django 5.2 on 2026-08-07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tnkreport",
            name="master_snapshot_captured_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name="ReportMasterSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("section_code", models.CharField(max_length=40)),
                ("entry_key", models.CharField(max_length=50)),
                ("source_model", models.CharField(max_length=120)),
                ("source_identifier", models.CharField(max_length=80)),
                ("summary", models.CharField(max_length=255)),
                ("values", models.JSONField(default=dict)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                ("report", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="master_snapshots", to="reporting.tnkreport")),
            ],
            options={
                "ordering": ("section_code", "entry_key", "pk"),
                "indexes": [models.Index(fields=["report", "section_code", "entry_key"], name="master_snapshot_lookup_idx")],
                "constraints": [models.UniqueConstraint(fields=("report", "section_code", "entry_key", "source_identifier"), name="unique_report_master_snapshot")],
            },
        ),
    ]
