# Generated by Django 5.2 on 2026-08-06 01:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IVDPProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('project_code', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=200)),
                ('project_category', models.CharField(max_length=80)),
                ('problem_being_addressed', models.TextField()),
                ('baseline_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('measurement_unit', models.CharField(blank=True, max_length=40)),
                ('priority', models.CharField(max_length=20)),
                ('responsible_person', models.CharField(blank=True, max_length=160)),
                ('responsible_organisation', models.CharField(blank=True, max_length=160)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('approved_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('actual_expenditure', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('currency_code', models.CharField(default='FJD', max_length=3)),
                ('funding_source', models.CharField(blank=True, max_length=160)),
                ('project_status', models.CharField(max_length=40)),
                ('physical_progress_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('financial_progress_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('expected_beneficiaries', models.PositiveIntegerField(blank=True, null=True)),
                ('male_beneficiaries', models.PositiveIntegerField(blank=True, null=True)),
                ('female_beneficiaries', models.PositiveIntegerField(blank=True, null=True)),
                ('youth_beneficiaries', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ivdp_projects', to='locations.village')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=180)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('percentage_weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestones', to='projects.ivdpproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IVDPProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('reporting_date', models.DateField()),
                ('work_completed', models.TextField()),
                ('progress_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('expenditure_to_date', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('materials_received', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('next_activity', models.TextField(blank=True)),
                ('next_activity_due_date', models.DateField(blank=True, null=True)),
                ('risk_level', models.CharField(max_length=20)),
                ('evidence_document', models.FileField(blank=True, null=True, upload_to='projects/%Y/%m/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_records', to='projects.ivdpproject')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_progress', to='reporting.tnkreport')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.projectmilestone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('risk_type', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('likelihood', models.CharField(max_length=20)),
                ('impact', models.CharField(max_length=20)),
                ('mitigation', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='projects.ivdpproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='ivdpproject',
            constraint=models.UniqueConstraint(fields=('village', 'project_code'), name='unique_village_project_code'),
        ),
    ]
