from django.db import models
from apps.core.models import UUIDTimeStampedModel
class ClimateImpactObservation(UUIDTimeStampedModel):
    village=models.ForeignKey("locations.Village",on_delete=models.PROTECT,related_name="climate_observations"); report=models.ForeignKey("reporting.TNKReport",on_delete=models.PROTECT,related_name="climate_observations"); hazard_type=models.CharField(max_length=80); observation_date=models.DateField(); latitude=models.DecimalField(max_digits=9,decimal_places=6,null=True,blank=True); longitude=models.DecimalField(max_digits=9,decimal_places=6,null=True,blank=True); severity=models.CharField(max_length=20); frequency=models.CharField(max_length=40,blank=True); households_affected=models.PositiveIntegerField(null=True,blank=True); population_affected=models.PositiveIntegerField(null=True,blank=True); farmland_affected=models.DecimalField(max_digits=14,decimal_places=2,null=True,blank=True); infrastructure_affected=models.TextField(blank=True); estimated_damage_value=models.DecimalField(max_digits=16,decimal_places=2,null=True,blank=True); currency_code=models.CharField(max_length=3,default="FJD"); description=models.TextField(); evidence_document=models.FileField(upload_to="climate/%Y/%m/",null=True,blank=True)
class ClimateResponseAction(UUIDTimeStampedModel):
    impact_observation=models.ForeignKey(ClimateImpactObservation,on_delete=models.CASCADE,related_name="response_actions"); action=models.TextField(); responsible_party=models.CharField(max_length=160); start_date=models.DateField(null=True,blank=True); due_date=models.DateField(null=True,blank=True); completion_date=models.DateField(null=True,blank=True); status=models.CharField(max_length=30); cost=models.DecimalField(max_digits=14,decimal_places=2,null=True,blank=True); currency_code=models.CharField(max_length=3,default="FJD"); funding_source=models.CharField(max_length=160,blank=True)
class VillageDisasterPreparedness(UUIDTimeStampedModel):
    village=models.OneToOneField("locations.Village",on_delete=models.PROTECT,related_name="disaster_preparedness"); disaster_plan_available=models.BooleanField(null=True,blank=True); plan_document=models.FileField(upload_to="disaster/plans/",null=True,blank=True); plan_last_updated=models.DateField(null=True,blank=True); disaster_committee_active=models.BooleanField(null=True,blank=True); emergency_contacts_available=models.BooleanField(null=True,blank=True); evacuation_drill_date=models.DateField(null=True,blank=True); warning_system_available=models.BooleanField(null=True,blank=True); emergency_supplies_available=models.BooleanField(null=True,blank=True); vulnerable_people_register_available=models.BooleanField(null=True,blank=True); last_reviewed=models.DateField(null=True,blank=True)
class EvacuationCentre(UUIDTimeStampedModel):
    village=models.ForeignKey("locations.Village",on_delete=models.PROTECT,related_name="evacuation_centres"); name=models.CharField(max_length=160); latitude=models.DecimalField(max_digits=9,decimal_places=6,null=True,blank=True); longitude=models.DecimalField(max_digits=9,decimal_places=6,null=True,blank=True); building_material=models.CharField(max_length=80,blank=True); capacity=models.PositiveIntegerField(null=True,blank=True); separate_male_female_restrooms=models.BooleanField(null=True,blank=True); accessibility_status=models.CharField(max_length=40); water_available=models.BooleanField(null=True,blank=True); sanitation_available=models.BooleanField(null=True,blank=True); condition=models.CharField(max_length=30); is_active=models.BooleanField(default=True)
class DisasterIncident(UUIDTimeStampedModel):
    village=models.ForeignKey("locations.Village",on_delete=models.PROTECT,related_name="disaster_incidents"); report=models.ForeignKey("reporting.TNKReport",on_delete=models.PROTECT,related_name="disaster_incidents"); incident_type=models.CharField(max_length=80); incident_date=models.DateField(); warning_received=models.BooleanField(null=True,blank=True); people_evacuated=models.PositiveIntegerField(null=True,blank=True); injuries=models.PositiveIntegerField(null=True,blank=True); deaths=models.PositiveIntegerField(null=True,blank=True); houses_damaged=models.PositiveIntegerField(null=True,blank=True); houses_destroyed=models.PositiveIntegerField(null=True,blank=True); estimated_loss=models.DecimalField(max_digits=16,decimal_places=2,null=True,blank=True); currency_code=models.CharField(max_length=3,default="FJD"); response_time_minutes=models.PositiveIntegerField(null=True,blank=True); assistance_received=models.BooleanField(null=True,blank=True); assistance_provider=models.CharField(max_length=160,blank=True); evidence_document=models.FileField(upload_to="disaster/incidents/%Y/%m/",null=True,blank=True)
