# Generated by Django 5.2 on 2026-08-06 01:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('position', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('joined_date', models.DateField()),
                ('left_date', models.DateField(blank=True, null=True)),
                ('training_received', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('decision', models.TextField()),
                ('responsible_person', models.CharField(blank=True, max_length=200)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='open', max_length=30)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reason_delayed', models.TextField(blank=True)),
                ('evidence_document', models.FileField(blank=True, null=True, upload_to='decisions/%Y/%m/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficialAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('appointment_date', models.DateField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('confirmation_status', models.CharField(default='pending', max_length=40)),
                ('appointment_reference', models.CharField(blank=True, max_length=150)),
                ('is_current', models.BooleanField(default=True)),
                ('change_reason', models.TextField(blank=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='officials/%Y/%m/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficialRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_fj', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PersonReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('confidentiality_level', models.CharField(choices=[('internal', 'Internal'), ('confidential', 'Confidential'), ('highly_restricted', 'Highly restricted')], default='confidential', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=160)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('delivery_method', models.CharField(blank=True, max_length=80)),
                ('target_group', models.CharField(blank=True, max_length=120)),
                ('male_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('female_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('youth_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('participants_with_disability', models.PositiveIntegerField(blank=True, null=True)),
                ('total_completed', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency_code', models.CharField(default='FJD', max_length=3)),
                ('funding_source', models.CharField(blank=True, max_length=160)),
                ('expected_outcome', models.TextField(blank=True)),
                ('actual_outcome', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('evidence_document', models.FileField(blank=True, null=True, upload_to='training/%Y/%m/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingOutcomeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('review_date', models.DateField()),
                ('participants_applying_skills', models.PositiveIntegerField(blank=True, null=True)),
                ('projects_started', models.PositiveIntegerField(blank=True, null=True)),
                ('businesses_started', models.PositiveIntegerField(blank=True, null=True)),
                ('outcome_rating', models.CharField(max_length=30)),
                ('challenges', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VillageCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('committee_type', models.CharField(choices=[('development', 'Development'), ('health', 'Health'), ('water', 'Water'), ('natural_resources_disaster', 'Natural Resources and Disaster'), ('education', 'Education'), ('youth', 'Youth'), ('women', 'Women'), ('law_order', 'Law and Order')], max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('formed_date', models.DateField(blank=True, null=True)),
                ('dissolved_date', models.DateField(blank=True, null=True)),
                ('mandate', models.TextField(blank=True)),
                ('constitution_available', models.BooleanField(blank=True, null=True)),
                ('annual_plan_available', models.BooleanField(blank=True, null=True)),
                ('bank_account_available', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VillageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('visit_type', models.CharField(max_length=80)),
                ('officer_name', models.CharField(max_length=200)),
                ('organisation', models.CharField(max_length=160)),
                ('visit_date', models.DateField()),
                ('purpose', models.TextField()),
                ('findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_due_date', models.DateField(blank=True, null=True)),
                ('follow_up_status', models.CharField(blank=True, max_length=30)),
                ('evidence_document', models.FileField(blank=True, null=True, upload_to='visits/%Y/%m/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommitteeMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('meeting_date', models.DateField()),
                ('total_attendance', models.PositiveIntegerField()),
                ('male_attendance', models.PositiveIntegerField(blank=True, null=True)),
                ('female_attendance', models.PositiveIntegerField(blank=True, null=True)),
                ('youth_attendance', models.PositiveIntegerField(blank=True, null=True)),
                ('disability_attendance', models.PositiveIntegerField(blank=True, null=True)),
                ('quorum_achieved', models.BooleanField(blank=True, null=True)),
                ('minutes_available', models.BooleanField(blank=True, null=True)),
                ('evidence_document', models.FileField(blank=True, null=True, upload_to='meetings/%Y/%m/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='committee_meetings', to='reporting.tnkreport')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
