# Generated by Django 5.2 on 2026-08-06 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('governance', '0001_initial'),
        ('locations', '0001_initial'),
        ('population', '0001_initial'),
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='population.agegroup'),
        ),
        migrations.AddField(
            model_name='meetingdecision',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='governance.committeemeeting'),
        ),
        migrations.AddField(
            model_name='officialappointment',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='official_appointments', to='locations.village'),
        ),
        migrations.AddField(
            model_name='officialappointment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='governance.officialrole'),
        ),
        migrations.AddField(
            model_name='personreference',
            name='home_village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='locations.village'),
        ),
        migrations.AddField(
            model_name='officialappointment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='governance.personreference'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='committee_memberships', to='governance.personreference'),
        ),
        migrations.AddField(
            model_name='committeemeeting',
            name='chaired_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='governance.personreference'),
        ),
        migrations.AddField(
            model_name='trainingactivity',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_activities', to='reporting.tnkreport'),
        ),
        migrations.AddField(
            model_name='trainingactivity',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_activities', to='locations.village'),
        ),
        migrations.AddField(
            model_name='trainingoutcomereview',
            name='reviewed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingoutcomereview',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_reviews', to='governance.trainingactivity'),
        ),
        migrations.AddField(
            model_name='villagecommittee',
            name='chairperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chaired_committees', to='governance.personreference'),
        ),
        migrations.AddField(
            model_name='villagecommittee',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secretary_committees', to='governance.personreference'),
        ),
        migrations.AddField(
            model_name='villagecommittee',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='committees', to='locations.village'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='governance.villagecommittee'),
        ),
        migrations.AddField(
            model_name='committeemeeting',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='governance.villagecommittee'),
        ),
        migrations.AddField(
            model_name='villagevisit',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='reporting.tnkreport'),
        ),
        migrations.AddField(
            model_name='villagevisit',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='locations.village'),
        ),
    ]
