# Generated by Django 5.2 on 2026-08-06 01:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_en', models.CharField(max_length=50)),
                ('name_fj', models.CharField(blank=True, max_length=50)),
                ('minimum_age', models.PositiveSmallIntegerField()),
                ('maximum_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='PopulationMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('movement_type', models.CharField(choices=[('birth', 'Birth'), ('death', 'Death'), ('moved_in', 'Moved in'), ('moved_out', 'Moved out'), ('temporarily_left', 'Temporarily left'), ('returned', 'Returned')], max_length=30)),
                ('movement_date', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('count', models.PositiveIntegerField()),
                ('origin_or_destination', models.CharField(blank=True, max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('data_source', models.CharField(choices=[('physical_count', 'Physical count'), ('household_register', 'Household register'), ('village_register', 'Village register'), ('committee_register', 'Committee register'), ('village_nurse', 'Village nurse'), ('police_record', 'Police record'), ('government_department', 'Government department'), ('interview', 'Interview'), ('estimate', 'Estimate'), ('other', 'Other')], max_length=40)),
                ('verified', models.BooleanField(default=False)),
                ('age_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='population.agegroup')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='population_movements', to='reporting.reportingperiod')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='population_movements', to='locations.village')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('household_code', models.CharField(max_length=50)),
                ('household_head_name', models.CharField(max_length=200)),
                ('household_size', models.PositiveIntegerField(blank=True, null=True)),
                ('male_count', models.PositiveIntegerField(blank=True, null=True)),
                ('female_count', models.PositiveIntegerField(blank=True, null=True)),
                ('child_count', models.PositiveIntegerField(blank=True, null=True)),
                ('elderly_count', models.PositiveIntegerField(blank=True, null=True)),
                ('disability_count', models.PositiveIntegerField(blank=True, null=True)),
                ('primary_livelihood', models.CharField(blank=True, max_length=120)),
                ('housing_type', models.CharField(blank=True, max_length=120)),
                ('water_source', models.CharField(blank=True, max_length=120)),
                ('toilet_type', models.CharField(blank=True, max_length=120)),
                ('energy_source', models.CharField(blank=True, max_length=120)),
                ('vulnerability_status', models.CharField(blank=True, max_length=80)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending_verification', 'Pending verification'), ('verified', 'Verified'), ('disputed', 'Disputed'), ('rejected', 'Rejected')], default='unverified', max_length=30)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='households', to='locations.village')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('village', 'household_code', 'effective_from'), name='unique_household_effective_record')],
            },
        ),
        migrations.CreateModel(
            name='PopulationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('measurement_date', models.DateField()),
                ('measurement_unit', models.CharField(blank=True, max_length=40)),
                ('data_source', models.CharField(choices=[('physical_count', 'Physical count'), ('household_register', 'Household register'), ('village_register', 'Village register'), ('committee_register', 'Committee register'), ('village_nurse', 'Village nurse'), ('police_record', 'Police record'), ('government_department', 'Government department'), ('interview', 'Interview'), ('estimate', 'Estimate'), ('other', 'Other')], max_length=40)),
                ('collection_method', models.CharField(max_length=80)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending_verification', 'Pending verification'), ('verified', 'Verified'), ('disputed', 'Disputed'), ('rejected', 'Rejected')], default='unverified', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('confidence_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('gender', models.CharField(max_length=30)),
                ('resident_status', models.CharField(choices=[('permanent_resident', 'Permanent resident'), ('temporary_resident', 'Temporary resident'), ('away_for_education', 'Away for education'), ('away_for_employment', 'Away for employment'), ('temporarily_absent', 'Temporarily absent'), ('unknown', 'Unknown')], max_length=30)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='population.agegroup')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='population_snapshots', to='reporting.tnkreport')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='population_snapshots', to='locations.village')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('report', 'age_group', 'gender', 'resident_status'), name='unique_population_snapshot_grain')],
            },
        ),
    ]
