# Generated by Django 5.2 on 2026-08-06 01:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_full_name', models.CharField(max_length=200)),
                ('user_role', models.CharField(max_length=100)),
                ('action_type', models.CharField(choices=[('submit', 'Submit'), ('comment', 'Comment'), ('request_correction', 'Request Correction'), ('return', 'Return'), ('forward', 'Forward'), ('verify', 'Verify'), ('approve', 'Approve'), ('reject', 'Reject'), ('reopen', 'Reopen'), ('lock', 'Lock'), ('archive', 'Archive')], max_length=30)),
                ('from_status', models.CharField(max_length=40)),
                ('to_status', models.CharField(max_length=40)),
                ('comment', models.TextField(blank=True)),
                ('digital_acknowledgement', models.BooleanField(default=False)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to='reporting.tnkreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinalDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_text', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('declared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='final_declaration', to='reporting.tnkreport')),
            ],
        ),
    ]
