# Generated by Django 5.2 on 2026-08-26 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_evidencedocument_capture_metadata'),
        ('reporting', '0003_report_amendments'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(max_length=40)),
                ('entry_key', models.CharField(max_length=50)),
                ('record_identifier', models.CharField(max_length=64)),
                ('stage', models.CharField(choices=[('observation', 'Observation'), ('before', 'Before'), ('progress', 'Progress'), ('after', 'After')], default='observation', max_length=20)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record_photo', to='documents.evidencedocument')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_photos', to='reporting.tnkreport')),
            ],
            options={
                'indexes': [models.Index(fields=['report', 'section_code', 'entry_key', 'record_identifier'], name='record_photo_target_idx')],
            },
        ),
    ]
