# Generated by Django 5.2 on 2026-08-06 00:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_fj', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name_en',),
            },
        ),
        migrations.CreateModel(
            name='Tikina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=20)),
                ('name_en', models.CharField(max_length=120)),
                ('name_fj', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tikina', to='locations.province')),
            ],
            options={
                'ordering': ('province__name_en', 'name_en'),
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=20)),
                ('name_en', models.CharField(max_length=120)),
                ('name_fj', models.CharField(blank=True, max_length=120)),
                ('island_name', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('postal_address', models.TextField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('tikina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villages', to='locations.tikina')),
            ],
            options={
                'ordering': ('tikina__name_en', 'name_en'),
            },
        ),
        migrations.AddConstraint(
            model_name='tikina',
            constraint=models.UniqueConstraint(fields=('province', 'code'), name='unique_tikina_code_per_province'),
        ),
        migrations.AddConstraint(
            model_name='village',
            constraint=models.UniqueConstraint(fields=('tikina', 'code'), name='unique_village_code_per_tikina'),
        ),
    ]
