# Generated by Django 5.2 on 2026-08-06 01:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('section', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('information', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('configurable_parameters', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='DataQualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('section', models.CharField(max_length=40)),
                ('field_name', models.CharField(blank=True, max_length=120)),
                ('severity', models.CharField(choices=[('information', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('current_value', models.TextField(blank=True)),
                ('previous_value', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_comment', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_issues', to='reporting.tnkreport')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_quality.dataqualityrule')),
            ],
            options={
                'indexes': [models.Index(fields=['report', 'resolved', 'severity'], name='quality_report_open_idx')],
            },
        ),
    ]
