# Generated by Django 5.2 on 2026-08-06 01:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateImpactObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('hazard_type', models.CharField(max_length=80)),
                ('observation_date', models.DateField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('severity', models.CharField(max_length=20)),
                ('frequency', models.CharField(blank=True, max_length=40)),
                ('households_affected', models.PositiveIntegerField(blank=True, null=True)),
                ('population_affected', models.PositiveIntegerField(blank=True, null=True)),
                ('farmland_affected', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('infrastructure_affected', models.TextField(blank=True)),
                ('estimated_damage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('currency_code', models.CharField(default='FJD', max_length=3)),
                ('description', models.TextField()),
                ('evidence_document', models.FileField(blank=True, null=True, upload_to='climate/%Y/%m/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='climate_observations', to='reporting.tnkreport')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='climate_observations', to='locations.village')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClimateResponseAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('action', models.TextField()),
                ('responsible_party', models.CharField(max_length=160)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=30)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency_code', models.CharField(default='FJD', max_length=3)),
                ('funding_source', models.CharField(blank=True, max_length=160)),
                ('impact_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_actions', to='resilience.climateimpactobservation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisasterIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('incident_type', models.CharField(max_length=80)),
                ('incident_date', models.DateField()),
                ('warning_received', models.BooleanField(blank=True, null=True)),
                ('people_evacuated', models.PositiveIntegerField(blank=True, null=True)),
                ('injuries', models.PositiveIntegerField(blank=True, null=True)),
                ('deaths', models.PositiveIntegerField(blank=True, null=True)),
                ('houses_damaged', models.PositiveIntegerField(blank=True, null=True)),
                ('houses_destroyed', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('currency_code', models.CharField(default='FJD', max_length=3)),
                ('response_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('assistance_received', models.BooleanField(blank=True, null=True)),
                ('assistance_provider', models.CharField(blank=True, max_length=160)),
                ('evidence_document', models.FileField(blank=True, null=True, upload_to='disaster/incidents/%Y/%m/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disaster_incidents', to='reporting.tnkreport')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disaster_incidents', to='locations.village')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvacuationCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=160)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('building_material', models.CharField(blank=True, max_length=80)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('separate_male_female_restrooms', models.BooleanField(blank=True, null=True)),
                ('accessibility_status', models.CharField(max_length=40)),
                ('water_available', models.BooleanField(blank=True, null=True)),
                ('sanitation_available', models.BooleanField(blank=True, null=True)),
                ('condition', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evacuation_centres', to='locations.village')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VillageDisasterPreparedness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('disaster_plan_available', models.BooleanField(blank=True, null=True)),
                ('plan_document', models.FileField(blank=True, null=True, upload_to='disaster/plans/')),
                ('plan_last_updated', models.DateField(blank=True, null=True)),
                ('disaster_committee_active', models.BooleanField(blank=True, null=True)),
                ('emergency_contacts_available', models.BooleanField(blank=True, null=True)),
                ('evacuation_drill_date', models.DateField(blank=True, null=True)),
                ('warning_system_available', models.BooleanField(blank=True, null=True)),
                ('emergency_supplies_available', models.BooleanField(blank=True, null=True)),
                ('vulnerable_people_register_available', models.BooleanField(blank=True, null=True)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('village', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disaster_preparedness', to='locations.village')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
