# Generated by Django 5.2 on 2026-08-06 01:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('governance', '0002_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraditionalTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('title_type', models.CharField(max_length=80)),
                ('title_name', models.CharField(max_length=160)),
                ('status', models.CharField(max_length=30)),
                ('vacancy_start_date', models.DateField(blank=True, null=True)),
                ('confirmation_stage', models.CharField(choices=[('vacant', 'Vacant'), ('community_discussion', 'Community Discussion'), ('village_meeting_completed', 'Village Meeting Completed'), ('documentation_in_progress', 'Documentation In Progress'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('confirmed', 'Confirmed'), ('disputed', 'Disputed')], max_length=40)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('next_action', models.TextField(blank=True)),
                ('responsible_party', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CulturalKnowledgeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('knowledge_category', models.CharField(max_length=80)),
                ('knowledge_name', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('number_of_knowledge_holders', models.PositiveIntegerField(blank=True, null=True)),
                ('youngest_knowledge_holder_age', models.PositiveIntegerField(blank=True, null=True)),
                ('transmission_status', models.CharField(max_length=40)),
                ('preservation_activity', models.TextField(blank=True)),
                ('activity_frequency', models.CharField(blank=True, max_length=80)),
                ('youth_participation', models.BooleanField(blank=True, null=True)),
                ('documentation_available', models.BooleanField(blank=True, null=True)),
                ('evidence_document', models.FileField(blank=True, null=True, upload_to='culture/%Y/%m/')),
                ('risk_level', models.CharField(choices=[('secure', 'Secure'), ('requires_support', 'Requires Support'), ('at_risk', 'At Risk'), ('critically_at_risk', 'Critically At Risk')], max_length=30)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cultural_knowledge', to='locations.village')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TraditionalTitleAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('confirmation_reference', models.CharField(blank=True, max_length=160)),
                ('is_current', models.BooleanField(default=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traditional_appointments', to='governance.personreference')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='culture.traditionaltitle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TraditionalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('unit_type', models.CharField(choices=[('yavusa', 'Yavusa'), ('mataqali', 'Mataqali'), ('tokatoka', 'Tokatoka'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traditional_units', to='locations.village')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='traditionaltitle',
            name='traditional_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titles', to='culture.traditionalunit'),
        ),
    ]
